"""initial schema

Revision ID: 8c021f58f2b0
Revises: 
Create Date: 2026-02-11 13:23:17.550182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c021f58f2b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('chess_com_url', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rapid_rating', sa.Integer(), nullable=True),
    sa.Column('blitz_rating', sa.Integer(), nullable=True),
    sa.Column('bullet_rating', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_games_fetched', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('chess_com_game_url', sa.String(length=200), nullable=False),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('white_username', sa.String(length=50), nullable=False),
    sa.Column('black_username', sa.String(length=50), nullable=False),
    sa.Column('player_color', sa.String(length=10), nullable=False),
    sa.Column('white_rating', sa.Integer(), nullable=True),
    sa.Column('black_rating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('player_result', sa.String(length=10), nullable=False),
    sa.Column('eco', sa.String(length=10), nullable=True),
    sa.Column('opening_name', sa.String(length=200), nullable=True),
    sa.Column('time_control', sa.String(length=20), nullable=True),
    sa.Column('time_class', sa.String(length=20), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_moves', sa.Integer(), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chess_com_game_url')
    )
    op.create_index('idx_player_played_at', 'games', ['player_id', 'played_at'], unique=False)
    op.create_index(op.f('ix_games_is_analyzed'), 'games', ['is_analyzed'], unique=False)
    op.create_index(op.f('ix_games_player_id'), 'games', ['player_id'], unique=False)
    op.create_table('player_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_game_count', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_archetype', sa.String(length=50), nullable=True),
    sa.Column('secondary_archetype', sa.String(length=50), nullable=True),
    sa.Column('archetype_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('radar_chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregated_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weakness_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rushing_score', sa.Float(), nullable=True),
    sa.Column('weakest_phase', sa.String(length=20), nullable=True),
    sa.Column('coaching_summary', sa.Text(), nullable=True),
    sa.Column('coaching_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('analysis_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_acpl', sa.Float(), nullable=False),
    sa.Column('opponent_acpl', sa.Float(), nullable=False),
    sa.Column('player_accuracy', sa.Float(), nullable=True),
    sa.Column('blunder_count', sa.Integer(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('inaccuracy_count', sa.Integer(), nullable=False),
    sa.Column('opening_acpl', sa.Float(), nullable=True),
    sa.Column('middlegame_acpl', sa.Float(), nullable=True),
    sa.Column('endgame_acpl', sa.Float(), nullable=True),
    sa.Column('book_deviation_move', sa.Integer(), nullable=True),
    sa.Column('book_deviation_san', sa.String(length=10), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_game_id', sa.Integer(), nullable=True),
    sa.Column('context_move_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('game_chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_index', sa.Integer(), nullable=False),
    sa.Column('is_white', sa.Boolean(), nullable=False),
    sa.Column('san', sa.String(length=10), nullable=False),
    sa.Column('uci', sa.String(length=10), nullable=False),
    sa.Column('fen_before', sa.String(length=100), nullable=False),
    sa.Column('fen_after', sa.String(length=100), nullable=False),
    sa.Column('best_move_uci', sa.String(length=10), nullable=True),
    sa.Column('best_move_san', sa.String(length=10), nullable=True),
    sa.Column('score_before_cp', sa.Integer(), nullable=True),
    sa.Column('score_after_cp', sa.Integer(), nullable=True),
    sa.Column('centipawn_loss', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('BRILLIANT', 'GOOD', 'BOOK', 'INACCURACY', 'MISTAKE', 'BLUNDER', name='moveclassification'), nullable=False),
    sa.Column('clock_seconds', sa.Float(), nullable=True),
    sa.Column('game_phase', sa.Enum('OPENING', 'MIDDLEGAME', 'ENDGAME', name='gamephase'), nullable=True),
    sa.Column('engine_line', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_move', 'move_evaluations', ['game_id', 'move_index'], unique=False)
    op.create_index(op.f('ix_move_evaluations_game_id'), 'move_evaluations', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_move_evaluations_game_id'), table_name='move_evaluations')
    op.drop_index('idx_game_move', table_name='move_evaluations')
    op.drop_table('move_evaluations')
    op.drop_table('game_chunk_embeddings')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('idx_session_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('analysis_summaries')
    op.drop_table('player_analyses')
    op.drop_index(op.f('ix_games_player_id'), table_name='games')
    op.drop_index(op.f('ix_games_is_analyzed'), table_name='games')
    op.drop_index('idx_player_played_at', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
